### PR TITLE
UI-13 add ace mapping for each config content type

### PR DESCRIPTION
**Pull request by etolbakov**

### CODE REVIEW

**Comment by BrunoBonacci** [comment]
it works nicely but for some reason it stores the original version not the edited one.
steps:

  - read a configuration entry
  - click on Edit
  - make some changes
  - click on Save
  - read the saved entry
  - **Expected**: new value, **Found**: old value

**Comment by etolbakov** [comment]
ok, got it. Thanks!
I had the same issue with "Copy to clipboard", resolved it there.

**Comment by BrunoBonacci** [comment]
I've checked again, and the issue seems to be present only for EDN. I don't know why.
Try it yourself, if you can't reproduce it with EDN, I will record a video too.

**Comment by BrunoBonacci** [comment]
here a recording of the issue

edn-issue

tried from a clean checkout of master

**Comment by etolbakov** [comment]
thanks, checking

**Comment by BrunoBonacci** [comment]
fixed by #26

**Pull request merged**
