### PR TITLE
UI-13 add initial edit implementation

### PR DESCRIPTION
**Pull request by etolbakov**

### CODE REVIEW

**Comment by etolbakov** [comment]
Great! Thank you for the feedback!
I'll take a look at the issues you've raised.

**Comment by BrunoBonacci** [comment]
It works nicely! well done, even the scrolling now it's fixed.
Please do let me know if I can merge this or you want to push more changes.

**Comment by etolbakov** [comment]
Great news!
I thought of a small refactoring(`new-entry-details-window` and `show-entry-window` are very similar) but let's merge it as soon as you are happy with the changes!

**Comment by BrunoBonacci** [comment]
`edn` should be just Clojure more (https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/clojure.js)

and this is for the properties https://github.com/ajaxorg/ace/blob/master/lib/ace/mode/properties.js

**Comment by etolbakov** [comment]
ok, got it! I'll fix it asap.

**Pull request merged**
